/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformOutput {
  code: string
  map?: string | undefined | null
}
export interface TransformConfig {
  reactRuntime?: boolean | undefined | null
  babelImport?: Array<BabelImportConfig> | undefined | null
}
export interface BabelImportConfig {
  fromSource: string
  replaceCss?: RepalceCssConfig | undefined | null
  replaceJs?: RepalceSpecConfig | undefined | null
}
export interface RepalceSpecConfig {
  replaceExpr: (...args: any[]) => any
  ignoreEsComponent?: Array<string> | undefined | null
  lower?: boolean | undefined | null
  camel2DashComponentName?: boolean | undefined | null
  transformToDefaultImport?: boolean | undefined | null
}
export interface RepalceCssConfig {
  ignoreStyleComponent?: Array<string> | undefined | null
  replaceExpr: (...args: any[]) => any
  lower?: boolean | undefined | null
  camel2DashComponentName?: boolean | undefined | null
}
export function transformBabelImport(code: string, config: TransformConfig, filename?: string | undefined | null, target?: string | undefined | null): TransformOutput
